name: "Nuevo evento (Iglesia)"
description: "Publicar un evento nuevo en la landing (actualiza events.json y desplaza los anteriores)."
title: "[Evento] "
labels: ["nuevo-evento"]

body:
  - type: input
    id: title
    attributes:
      label: "Título del evento"
      placeholder: "Ej: Jesús, la Luz del Mundo"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: "Fecha y hora"
      placeholder: "Enero 2026 · Fecha por confirmar"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Descripción"
      placeholder: "Escribe la descripción del evento..."
    validations:
      required: true

  - type: textarea
    id: image
    attributes:
      label: "Imagen del evento"
      description: |
        Adjunta la imagen aquí (arrastrar/pegar) para que se genere el link ![](...)
        IMPORTANTE: sube 1 sola imagen.
      placeholder: "Arrastra o pega la imagen aquí para que aparezca el link."
    validations:
      required: true
