name: "Nuevo evento (Iglesia)"
description: "Publicar un evento nuevo en la landing (actualiza events.json y desplaza los anteriores)."
title: "[Evento] "
labels: ["nuevo-evento"]
body:
  - type: input
    id: title
    attributes:
      label: "Título del evento"
      description: "Ej: Culto de Gratitud"
      placeholder: "Escribe el título"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: "Fecha y hora"
      description: "Usa el formato sugerido para que se vea bien en la web."
      placeholder: "31-12-2025 22:00 hrs"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Descripción"
      description: "Texto que aparecerá debajo del título."
      placeholder: "Escribe la descripción del evento..."
    validations:
      required: true

  - type: textarea
    id: image
    attributes:
      label: "Imagen del evento"
      description: |
        Adjunta la imagen aquí:
        - Arrastra y suelta la imagen en este cuadro, o pégala.
        - Debe quedar algo como: ![](https://....)
        IMPORTANTE: sube 1 sola imagen.
      placeholder: "Pega aquí la imagen (arrastrar/soltar) para que quede el link."
    validations:
      required: true
